In [5]:
import pandas as pd

In [3]:
students = [
    ["Alice", 85, 78, 85],
    ["Bob", 95, 88, 91],
    ["Charlie", 20, 29, 28]
]
print(type(students))
print(students)

<class 'list'>
[['Alice', 85, 78, 85], ['Bob', 95, 88, 91], ['Charlie', 20, 29, 28]]

In [7]:
students = [
    ["Alice", 21, "Pune", 85],
    ["Bob", 22, "Mumbai", 91],
    ["Charlie", 20, "Pune", 78]
]
print(students)

df = pd.DataFrame(
    students,
    columns=["Name", "Age", "City", "Score"]
)
print('\n')
print(df)

[['Alice', 21, 'Pune', 85], ['Bob', 22, 'Mumbai', 91], ['Charlie', 20, 'Pune', 78]]


      Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78

In [8]:
df.head()

      Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78

In [9]:
df.tail()

      Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78

In [11]:
df.shape

(3, 4)

In [13]:
df.columns

Index(['Name', 'Age', 'City', 'Score'], dtype='str')

In [16]:
df.dtypes

Name       str
Age      int64
City       str
Score    int64
dtype: object

In [17]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [21]:
df.describe()

        Age      Score
count   3.0   3.000000
mean   21.0  84.666667
std     1.0   6.506407
min    20.0  78.000000
25%    20.5  81.500000
50%    21.0  85.000000
75%    21.5  88.000000
max    22.0  91.000000

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
 3   Score   3 non-null      int64
dtypes: int64(2), str(2)
memory usage: 228.0 bytes

In [22]:
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str